### ISSUE TITLE
lab-5

### ISSUE THREAD

**Issue by rhrobin34** [rhrobin34/LAB-5#1]
#include <stdio.h>

int main() {
    int num1, num2, sum, difference;

    // Input two integers
    printf("Enter two numbers: ");
    scanf("%d %d", &num1, &num2);

    // Addition
    sum = num1 + num2;

    // Subtraction
    difference = num1 - num2;

    // Output the results
    printf("Sum: %d\n", sum);
    printf("Difference: %d\n", difference);

    return 0;
}

**Comment by rhrobin34** [comment]
1. multiply
2. division
3. prime
4. not prime

**Comment by Hossainmim** [comment]
#include <stdio.h>

int main() {
    int num1, num2, product;

    // Input two integers
    printf("Enter two numbers: ");
    scanf("%d %d", &num1, &num2);

    // Multiplication
    product = num1 * num2;

    // Output the result
    printf("Product: %d\n", product);

    return 0;
}
